import * as Joi from 'joi';

export const environmentValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'production').default('development'),
  PORT: Joi.number().port().default(3000),
  DATABASE_URL: Joi.string().uri({ scheme: ['postgresql', 'postgres'] }).required(),
  JWT_SECRET: Joi.string().min(32).required(),
  JWT_EXPIRES_IN: Joi.number().integer().positive().default(3600),
  AUTH_COOKIE_NAME: Joi.string().default('medical_crm_access'),
  COOKIE_SECURE: Joi.boolean().truthy('true').falsy('false').default(false),
  CORS_ORIGIN: Joi.string().allow('').default(''),
  LOG_LEVEL: Joi.string().valid('fatal', 'error', 'warn', 'log', 'debug', 'verbose').default('log'),
  SECURITY_ENFORCE_HTTPS: Joi.boolean().truthy('true').falsy('false').default(false),
  SECURITY_HSTS_MAX_AGE: Joi.number().integer().min(0).default(15552000),
  DUPLICATE_WINDOW_DAYS: Joi.number().integer().min(1).default(30),
  META_APP_ID: Joi.string().allow('').default(''),
  META_APP_SECRET: Joi.string().allow('').default(''),
  META_REDIRECT_URI: Joi.string().uri().allow('').default(''),
  META_WEBHOOK_VERIFY_TOKEN: Joi.string().allow('').default(''),
  META_TOKEN_ENCRYPTION_KEY: Joi.string().allow('').default(''),
  TIKTOK_APP_ID: Joi.string().allow('').default(''),
  TIKTOK_APP_SECRET: Joi.string().allow('').default(''),
  TIKTOK_REDIRECT_URI: Joi.string().uri().allow('').default(''),
  TIKTOK_TOKEN_ENCRYPTION_KEY: Joi.string().allow('').default(''),
  TIKTOK_API_BASE_URL: Joi.string().uri().allow('').default('https://business-api.tiktok.com/open_api/v1.3'),
  TIKTOK_OAUTH_AUTHORIZE_URL: Joi.string().uri().allow('').default(''),
  TIKTOK_OAUTH_TOKEN_URL: Joi.string().uri().allow('').default(''),
  TIKTOK_SCOPES: Joi.string().allow('').default('lead_management,advertiser_management'),
  SNAPCHAT_CLIENT_ID: Joi.string().allow('').default(''),
  SNAPCHAT_CLIENT_SECRET: Joi.string().allow('').default(''),
  SNAPCHAT_REDIRECT_URI: Joi.string().uri().allow('').default(''),
  SNAPCHAT_TOKEN_ENCRYPTION_KEY: Joi.string().allow('').default(''),
  SNAPCHAT_API_BASE_URL: Joi.string().uri().allow('').default('https://adsapi.snapchat.com/v1'),
  SNAPCHAT_OAUTH_AUTHORIZE_URL: Joi.string().uri().allow('').default(''),
  SNAPCHAT_OAUTH_TOKEN_URL: Joi.string().uri().allow('').default(''),
  SNAPCHAT_SCOPES: Joi.string().allow('').default('snapchat-marketing-api'),
});
